import mods.nei.NEI;
import minetweaker.item.IItemStack;

mods.nei.NEI.addEntry(<cobblemon:cr.pokemon.species>);
mods.nei.NEI.hide(<cobblemon:cr.pokemon.species>);

mods.nei.NEI.addEntry(<cobblemon:cr.moveeditor.filled>);
mods.nei.NEI.hide(<cobblemon:cr.moveeditor.filled>);

var NEIhide = [
    <cobblemon:cr.pokemon.full>,
	<minecraft:bedrock>,
	<lolidimensions:spectral_fire>,
	<lolidimensions:amber_fire>,
	<lolidimensions:rainbow_fire:*>,
	<lolidimensions:abyss_fire>,
	<lolidimensions:hell_fire>,
	<lolidimensions:soul_fire>,
	<lwsl:structure_transience>,
	<lolidimensions:spawner>,
	<loli_utility:Key:*>,
	<minecraft:written_book>,
	<minecraft:item_frame>,
	<minecraft:boat>,
	<minecraft:writable_book>,
	<minecraft:chest_minecart>,
	<minecraft:tnt_minecart>,
	<minecraft:hopper_minecart>,
	<minecraft:furnace_minecart>,
	<betterquesting:extra_life:1>,
	<betterquesting:extra_life:2>,
	<betterquesting:extra_life>,
	<betterquesting:guide_book>,
	<betterquesting:placeholder>,
	<betterquesting:submit_station>,
	<bq_standard:loot_chest>,
	<minecraft:command_block_minecart>,
	<minecraft:command_block>,
	<lolidimensions:hell_chest:*>,
	<lolidimensions:hell_chest_locked:*>,
	<lolidimensions:reserved_item_15:*>,
	<lolidimensions:hell_spawn_egg:*>,
	<lolidimensions:holy_spawn_egg:*>,
	<lolidimensions:holy_chest:*>,
	<lolidimensions:double_eternal_slab>,
	<lolidimensions:dungeon_altar_kiln>,
	<lolidimensions:dungeon_gate_simple>,
	<lolidimensions:holy_cobblestone_unbreakable>,
	<lolidimensions:holy_cobblestone_unbreakable_slab>,
	<lolidimensions:holy_cobblestone_unbreakable_stairs>,
	<lolidimensions:holy_cobblestone_unbreakable_wall>,
	<lolidimensions:holy_earth_unbreakable>,
	<lolidimensions:holy_grass_unbreakable>,
	<lolidimensions:holy_rock_brick_chiseled_unbreakable>,
	<lolidimensions:holy_rock_brick_cracked_unbreakable>,
	<lolidimensions:holy_rock_brick_cracked_unbreakable_slab>,
	<lolidimensions:holy_rock_brick_cracked_unbreakable_stairs>,
	<lolidimensions:holy_rock_brick_mossy_unbreakable>,
	<lolidimensions:holy_rock_brick_mossy_unbreakable_slab>,
	<lolidimensions:holy_rock_brick_mossy_unbreakable_stairs>,
	<lolidimensions:holy_rock_brick_unbreakable>,
	<lolidimensions:holy_rock_brick_unbreakable_slab>,
	<lolidimensions:holy_rock_brick_unbreakable_stairs>,
	<lolidimensions:holy_rock_brick_unbreakable_wall>,
	<lolidimensions:holy_rock_pillar_unbreakable>,
	<lolidimensions:holy_rock_smooth_unbreakable>,
	<lolidimensions:holy_rock_smooth_unbreakable_slab>,
	<lolidimensions:holy_rock_unbreakable>,
	<lolidimensions:holy_temple_core>,
	<lolidimensions:radiant_lamp_off>,
	<lolidungeons:dungeon_spawner>,
	<minecraft:portal>, 
	<minecraft:end_portal>, 
	<minecraft:nether_star>, 
	<minecraft:stone_slab:7>, 
	<minecraft:obsidian>,
	<minecraft:quartz_block>, 
	<minecraft:quartz_block:1>, 
	<minecraft:quartz_block:2>, 
	<minecraft:quartz_block:5>, 
	<minecraft:quartz_block:6>,
	<minecraft:quartz_stairs>, 	
	<lolidimensions:dragon_gate_wall:4>, 
	<lolidimensions:dragon_gate_wall:8>, 
	<lolidimensions:dragon_gate_wall:12>, 
	<lolidimensions:dragon_gate_crystal>, 
	<lolidimensions:dragon_gate_cannon>, 
	<lolidimensions:arcanite_bars>, 
	<lolidimensions:dragon_gate_barrier>, 
	<lolidimensions:dragon_gate_master_block>, 
	<lolidimensions:dragon_dungeon_exit_core>, 
	<lolidimensions:dragon_gate_wall>, 
	<lolidimensions:dragon_summon_pedestal>, 
	<lolidimensions:dragon_summon_pedestal:1>, 
	<lolidimensions:reserved_block_15>, 
	<minecraft:end_stone>, 
	<minecraft:end_portal_frame>, 
	<lwsl:structure_selector>, 
	<lwsl:structure_green>, 
	<lwsl:structure_blue>, 
	<lwsl:structure_red>, 
	<lolidimensions:dragon_gate_master_block>,
	<worldgen:cave_air>,
	<worldgen:void_air>, 
	<worldgen:bedrock>, 
	<minecraft:potion:*>,
	<minecraft:spawn_egg:*>,
	<loli_utility:setting_duplicator>,
	<loli_utility:structure_builder>,
	<loli_utility:picture_frame>,	
	<lolidimensions:hell_adamantium_ore>,
	<lolidimensions:hell_aluminum_ore>,
	<lolidimensions:hell_amber_ore>,
	<lolidimensions:hell_bedrock>,
	<lolidimensions:hell_bloodgem_ore>,
	<lolidimensions:hell_certus_quartz_ore>,
	<lolidimensions:hell_copper_ore>,
	<lolidimensions:hell_hellfish_ore>,
	<lolidimensions:hell_infernium_ore>,
	<lolidimensions:hell_iridium_ore>,
	<lolidimensions:hell_lead_ore>,
	<lolidimensions:hell_magnesium_ore>,
	<lolidimensions:hell_mithril_ore>,
	<lolidimensions:hell_netherite_ore>,
	<lolidimensions:hell_nickel_ore>,
	<lolidimensions:hell_nikolite_ore>,
	<lolidimensions:hell_osmium_ore>,
	<lolidimensions:hell_peridot_ore>,
	<lolidimensions:hell_sulfur_ore>,
	<lolidimensions:hell_tennantite_ore>,
	<lolidimensions:hell_tin_ore>,
	<lolidimensions:hell_titanium_ore>,
	<lolidimensions:hell_tungsten_ore>,
	<lolidimensions:hell_uranium_ore>,
	<lolidimensions:hell_platinum_ore>,
	<lolidimensions:hell_redstone_ore>,
	<lolidimensions:hell_ruby_ore>,
	<lolidimensions:hell_rutile_ore>,
	<lolidimensions:hell_salt_ore>,
	<lolidimensions:hell_saltpeter_ore>,
	<lolidimensions:hell_sapphire_ore>,
	<lolidimensions:hell_silver_ore>,
	<lolidimensions:hell_steel_ore>,	
	<loli_utility:event_end_stone>,
	<loli_utility:event_snow>,
	<loli_utility:Regeneration>,
	<loli_utility:InvisibilityDispel>,
	<loli_utility:Reservoir>,
	<minecraft:monster_egg>,
	<minecraft:monster_egg:*>,
	<loli_utility:ckey_stone:*>,	
	
	<lolidimensions:chaos_dragon_heart>,
	<lolidimensions:ice_dragon_heart>,
	<lolidimensions:fire_dragon_heart>,
	<lolidimensions:infinity_dragon_heart>,
	<lolidimensions:demonic_infinity_dragon_heart>,
	<lolidimensions:awakened_dragon_heart>,
	<lolidimensions:awakened_chaos_dragon_heart>,
	<lolidimensions:awakened_ice_dragon_heart>,
	<lolidimensions:awakened_fire_dragon_heart>,
	<lolidimensions:awakened_infinity_dragon_heart>,
	<lolidimensions:awakened_demonic_infinity_dragon_heart>,
	<lolidimensions:legendary_dragon_heart>,
	<lolidimensions:empty_dragon_blood_vessel>,
	<lolidimensions:dragon_blood>,
	<lolidimensions:chaos_dragon_blood>,
	<lolidimensions:ice_dragon_blood>,
	<lolidimensions:ice_dragon_blood>,
	<lolidimensions:fire_dragon_blood>,
	<lolidimensions:infinity_dragon_blood>,
	<lolidimensions:demonic_infinity_dragon_blood>,
	<lolidimensions:awakened_draconium_essence>,
	<lolidimensions:awakened_draconium_ingot>,
	<lolidimensions:awakened_draconium_nugget>,
	<lolidimensions:awakened_draconium_plate>,
	<lolidimensions:dragon_heart>,
	<lolidimensions:chaotic_draconium_essence>,
	<lolidimensions:chaotic_draconium_dust>,
	<lolidimensions:chaotic_draconium_ingot>,
	<lolidimensions:chaotic_draconium_plate>,
	<lolidimensions:ice_draconium_essence>,
	<lolidimensions:ice_draconium_dust>,
	<lolidimensions:ice_draconium_ingot>,
	<lolidimensions:ice_draconium_plate>,
	<lolidimensions:fire_draconium_essence>,
	<lolidimensions:fire_draconium_dust>,
	<lolidimensions:fire_draconium_ingot>,
	<lolidimensions:fire_draconium_plate>,
	<lolidimensions:infinity_draconium_essence>,
	<lolidimensions:infinity_draconium_dust>,
	<lolidimensions:infinity_draconium_ingot>,
	<lolidimensions:infinity_draconium_plate>,
	<lolidimensions:demonic_infinity_draconium_essence>,
	<lolidimensions:demonic_infinity_draconium_dust>,
	<lolidimensions:demonic_infinity_draconium_ingot>,
	<lolidimensions:demonic_infinity_draconium_plate>,
	<lolidimensions:draconium_plate>,	
	


	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	<lolidimensions:ender_fire>

] as IItemStack[];

for i, item in NEIhide {
	NEI.hide(item);
}
